[tool.poetry]
name = "astronomy-ml-project"
version = "0.1.0"
description = "Astronomy ML project using TensorFlow, Keras, MLflow, Prefect, and GCP."
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/yourusername/astronomy-ml-project"
keywords = ["machine-learning", "astronomy", "tensorflow", "keras"]

[tool.poetry.dependencies]
python = "^3.11"

# Primary dependencies
tensorflow = "^2.11.0"
keras = "^2.11.0"
mlflow = "^2.2.1"
prefect = "^2.8.4"
pandas = "^1.5.3"
numpy = "^1.23.5"
scikit-learn = "^1.2.1"
google-cloud-bigquery = "^3.4.2"
google-cloud-storage = "^2.7.0"
gunicorn = "^20.1.0"

[tool.poetry.dev-dependencies]
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
